name: CI

on:
  push:
    branches: '*'
    tags: '*'

jobs:
  test:
    name: Test
    runs-on: macos-10.15

    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Download disk archive
        run: curl -L -o resources.tar https://github.com/jacob-carlborg/xhyve-test/releases/download/qcow2/resources.tar

      - name: Unarchive disk
        run: tar xf resources.tar

      - name: List files
        run: ls -lh

      - name: Convert qcow2 disk to raw disk
        run: ./qemu-img convert -f qcow2 -O raw disk.qcow2 disk.raw

      # - name: Run CI
      #   run: ./ci.rb
