name: CI

on:
  push:
    branches: '*'

jobs:
  test:
    name: Test
    runs-on: macos-10.15

    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install Xhyve
        run: brew install xhyve --HEAD

      - name: Download disk archive
        run: curl -L -o disk.tar.xz https://github.com/jacob-carlborg/xhyve-test/releases/download/test/disk.tar.xz

      - name: Unarchive disk
        run: XZ_OPT="$XZ_OPT --threads=0" tar xf disk.tar.xz

      - name: Run CI
        run: ./run.sh -M
