name: CI

on:
  push:
    branches: '*'
    tags: '*'

jobs:
  test:
    name: Test
    services:
      qemu-install:
        image: tonistiigi/binfmt:latest
        options: --privileged
    container:
      image: ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: uname
        run: uname -a
        # run: docker run --rm --platform linux/arm64 ubuntu uname -a
