name: CI

on:
  push:
    branches: '*'
    tags: '*'

jobs:
  test:
    runs-on: macOS-latest

    steps:
      - name: Number of cores
        run:  sysctl -n hw.logicalcpu

      - name: SPHardwareDataType
        run: system_profiler SPHardwareDataType
