name: CI

on:
  push:
    branches: '*'
    tags: '*'

jobs:
  test:
    name: Test
    container:
      image: ubuntu
      options: --platform arm64
    runs-on: ubuntu-latest

    steps:
      - name: uname
        run: uname -a
