name: CI

on:
  push:
    branches: '*'
    tags: '*'

jobs:
  test:
    name: Test
    container:
      image: ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Run Docker container
        run: uname -a
        # run: docker run --rm --platform linux/arm64 ubuntu uname -a
