name: CI

on:
  push:
    branches: '*'
    tags: '*'

jobs:
  test:
    name: Test
    # container:
    #   image: ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: uname
        run: |
          docker buildx create --platform linux/arm64 --name foobar --use
          docker buildx inspect --bootstrap --builder foobar
          docker buildx ls
          docker run -it --rm --platform linux/arm64 ubuntu uname -a
