name: CI

on:
  push:
    branches: '*'
    tags: '*'

jobs:
  test:
    name: Test
    # container:
    #   image: ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: uname
        run: docker buildx ls
