name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'
      - '*'

jobs:
  # build: # make sure build/ci work properly
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - run: |
  #         npm install
  #     - run: |
  #         npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: macos-10.15
    # runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          # path: action
      # - run: apt update && apt install -y net-tools
      - uses: ./
        with:
          milliseconds: 1000
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
      #   with:
      #     limit-access-to-actor: true
